### ISSUE TITLE
Kafka Docker Load Generator is still performing a health check on Rabbit MQ

### ISSUE THREAD

**Issue by allanmoso** [spring-cloud-stream-app-starters/load-generator#5]
I have a Spring Cloud Data Flow installation running in Kubernetes with Kafka as the messaging middleware.  While testing the load-generator source I've noticed that it is restarting often. The logs shows errors related to RabbitMQ. It looks like it is performing a Health Check for RabbitMQ and failing. This might be the cause of the restarts.

Version: `docker:springcloudstream/load-generator-source-kafka-10:1.3.1.RELEASE`

Log Snippet:
```
2018-12-05 14:10:06.644  WARN 1 --- [nio-8080-exec-7] o.s.b.a.health.RabbitHealthIndicator     : Health check failed

org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused (Connection refused)
        at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:62) ~[spring-rabbit-1.7.4.RELEASE.jar!/:na]
        at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:368) ~[spring-rabbit-1.7.4.RELEASE.jar!/:na]
        at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:573) ~[spring-rabbit-1.7.4.RELEASE.jar!/:na]
        at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1430) ~[spring-rabbit-1.7.4.RELEASE.jar!/:na]
        at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1411) ~[spring-rabbit-1.7.4.RELEASE.jar!/:na]
        at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1387) ~[spring-rabbit-1.7.4.RELEASE.jar!/:na]
        at org.springframework.boot.actuate.health.RabbitHealthIndicator.getVersion(RabbitHealthIndicator.java:49) ~[spring-boot-actuator-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.actuate.health.RabbitHealthIndicator.doHealthCheck(RabbitHealthIndicator.java:45) ~[spring-boot-actuator-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:43) ~[spring-boot-actuator-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:68) [spring-boot-actuator-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.actuate.endpoint.HealthEndpoint.invoke(HealthEndpoint.java:85) [spring-boot-actuator-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.getCurrentHealth(HealthMvcEndpoint.java:177) [spring-boot-actuator-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.getHealth(HealthMvcEndpoint.java:166) [spring-boot-actuator-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.invoke(HealthMvcEndpoint.java:143) [spring-boot-actuator-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
```

**Comment by sabbyanandan** [comment]
A Kafka app shouldn't interact with Rabbit in any capacity. We will review it on our side. Thanks for reporting.

**Comment by artembilan** [comment]
I see there is a Spring Integration AMQP dependency in this project: https://github.com/spring-cloud-stream-app-starters/load-generator/blob/master/spring-cloud-starter-stream-source-load-generator/pom.xml#L19.

Fully not clear why do we need it there...

I just believe that we really don't need it and that was a side effect after migration from Spring XD.
